# -*- coding: utf-8 -*-
"""last.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19yWvA_7YXsXf1scFZ251MD9IpCh9LqoK
"""

term = input("Please enter your current term: ")
if term.isalpha() == True or len(str(term)) > 1 or float(term) < 1:
  print("Invalid input for the current term.")
elif int(term) < 2:
  print("Your Erasmus score cannot be calculated before the 2nd term.")
else:
  credit = input("Please enter the total credits you earned before: ")
  if int(credit) < 0 or credit.isalpha() == True:
    print("Invalid input for the credits earned before.")
  elif int(term) == 2 and int(credit) < 34 or int(term) == 3 and int(credit) < 49 or int(term) > 3 and int(credit) < 58:
    print("Your Erasmus score cannot be calculated before you took the required amount of credits.")
  elif int(term) == 2 and int(credit) >= 34 or int(term) == 3 and int(credit) >=49 or int(term) > 3 and int(credit) >= 58:
    sps = input("Please enter the SPS101 letter grade equivalents: ")
    sps = sps.upper()
    if sps[0].isalpha() == False or sps[-1].isdigit() == False or "::" in sps or ";;" in sps or ":;" in sps or ";:" in sps:
      print("Invalid input for SPS101 letter grade sequence.")
    elif sps[0].isalpha() == True and sps[-1].isdigit() == True and "::" not in sps and ";;" not in sps and ":;" not in sps and ";:" not in sps:
      al = input("Please enter the AL102 letter grade equivalents: ")
      al = al.upper()
      if al[0].isalpha() == False or al[-1].isdigit() == False or "::" in al or ";;" in al or ":;" in al or ";:" in al:
        print("Invalid input for AL102 letter grade sequence.")
      elif al[0].isalpha() == True and al[-1].isdigit() == True and "::" not in al and ";;" not in al and ":;" not in al and ";:" not in al:
        grades = input("Please enter your SPS101 and AL102 letter grades: ")
        grades = grades.upper()
        if grades[0].isalpha() == True and grades[-1].isalpha() == True and grades[1] == ",":
          check_grades = True
        elif grades[0].isalpha() == True and grades[-1].isalpha() == True and grades[2] == ",":
          check_grades = True
        elif grades[0].isalpha() == True and grades[-2].isalpha() == True and grades[1] == ",":
          check_grades = True
        elif grades[0].isalpha() == True and grades[-2].isalpha() == True and grades[2] == ",":
          check_grades = True
        elif grades[0].isalpha() == True and grades[2] == "-" and grades[1] == ",":
          check_grades = True
        elif len(grades) == 4 and grades[0].isalpha() == True and grades[3] == "-" and grades[2] == ",":
          check_grades = True
        else:
          check_grades = False
        if check_grades == True:
          grade =grades.split(",")
          if grades[0] not in sps:
              print("Your SPS101 letter grade couldn't be found in point-scale.")
          elif grades[-1] not in al:
              print("Your AL102 letter grade couldn't be found in point-scale.")
          elif grades[0] in sps and grades[-1] in al:
            gpa = input("Please enter your current GPA: ")
            if 0 > float(gpa) or float(gpa) > 4:
              print("Your GPA needs to be in between 0-4.")
            elif 2.2 > float(gpa):
              print("Your GPA needs to be at least 2.2.")
            elif 2.2 <= float(gpa):
              sps_gradei = grades[0]
              sps_gradeii = sps.index(sps_gradei)
              if len(sps_gradei) == 1:
                sps_grade = sps[sps_gradeii+2: sps_gradeii+4]
                if sps_grade == 10:
                  sps_grade == 100
                else:
                  sps_grade = sps_grade
              elif len(sps_gradei) == 2:
                sps_grade = sps[sps_gradeii+3: sps_gradeii+5]
                if sps_grade == 10:
                  sps_grade == 100
                else:
                  sps_grade = sps_grade
              if grades[-1] == "-":
                al_gradei = "C"
              else:
                al_gradei = al_gradei
              al_gradei = grades[-1]
              al_gradeii = al.index(al_gradei)
              if len(al_gradei) == 1:
                al_grade = al[al_gradeii+2: al_gradeii+4]
                if al_grade == 10:
                  al_grade == 100
                else:
                  al_grade = al_grade
              elif len(al_gradei) == 2:
                al_grade = al[al_gradeii+3: al_gradeii+5]
                if al_grade == 10:
                  al_grade == 100
                else:
                  al_grade = al_grade
              eng_score = (int(sps_grade) * 0.4) + (int(al_grade) * 0.6)
              erasmus = (float(eng_score) * 0.5) + (float(gpa) * 25 * 0.5)
              print("Your final Erasmus score is,", erasmus)  
        elif check_grades == False:
          print("Invalid input for SPS101 and AL102 letter grades.")