# -*- coding: utf-8 -*-
"""suedaseker_the5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16WqjuGuFV8p_FkF7IZIYb1Em2r93Gj8t
"""

def levenshtein(str1, str2):
  size_x = len(str1) + 1
  size_y = len(str2) + 1
  matrix = []
  for i in range(size_x):
    temp = [0]*size_y
    matrix.append(temp)
  for i in range(size_x):
    matrix[i][0] = i
  for i in range(size_y):
    matrix[0][i] = i
  for x in range(1, size_x):
      for y in range(1, size_y):
          if str1[x-1] == str2[y-1]:
              matrix [x][y] = min(matrix[x-1][y] + 1, matrix[x-1][y-1], matrix[x][y-1] + 1)
          else:
            matrix [x][y] = min(matrix[x-1][y] + 1, matrix[x-1][y-1] + 1, matrix[x][y-1] + 1)
  return(matrix[size_x - 1][size_y - 1])

myfile = open("book.txt")
content = myfile.read()

plaintext = ""
for ch in content:
  if ch.isalpha() or ch == " ":
    plaintext += ch.lower()
  else:
    plaintext

d_count = {}
plaintext = plaintext.split(" ")

for ch in plaintext:
  if ch in d_count:
    d_count[ch] += 1
  else:
    d_count[ch] = 1

word1 = input("Please enter the word/words you want to check: ")

while word1 != "exit()":

  word1 = word1.split(" ")
  x = 0
  for word in word1:
    if word in plaintext:
      x += 1
    else:
      x
  if len(word1) == x:
    print("String you entered is correctly written!")
    word1 = input("Please enter the word/words you want to check: ")
  else:
    dl = {}
    for str1 in word1:
      for str2 in d_count.keys():
        result = levenshtein(str1, str2)
        dl[str2] = result
      minvalue = min(dl.values())
      count = 0
      correct = []
      for k, v in dl.items():
        if v == minvalue:
          correctw = k
          count += 1
          correct.append(correctw)
      if count == 1:
        idx = word1.index(str1)
        word1[idx] = correctw
      else:
        d_freq = {}
        for word in correct:
          d_freq[word] = d_count[word]
        maxvalue = max(d_freq.values())
        keys = []
        for k, v in d_freq.items():
          if v == maxvalue:
            keys.append(k)
        if len(keys) == 1:
          for k, v in d_freq.items():
            if v == maxvalue:
              correctw = k

          idx = word1.index(str1)
          word1[idx] = correctw
        else:
          list1 = sorted(keys)
          correctw = list1[0]

          idx = word1.index(str1)
          word1[idx] = correctw
          

    final = ""
    for w in word1:
      final += w+" "
    final = final[0:-1]
    print("Did you mean:", final)
    word1 = input("Please enter the word/words you want to check: ")

if word1 == "exit()":
  print("See you next time...")