# -*- coding: utf-8 -*-
"""suedaseker_the1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-XHq8g7s1IrorSYz12DlfgF_gUyJTmhz
"""

padd = int(input("Please enter the number of digits in padd-lock: "))
pc = int(input("Please enter the password length of the PC: "))
gb = float(input("Please enter the file size you want to transfer (GB): "))

pos_padd = 10 ** padd
pos_pc = 14 ** pc

padd_sec = pos_padd / 1000
pc_sec = pos_pc / 600000
gb_sec = (gb * 1024) / 60

h = ((padd_sec + pc_sec + gb_sec) // 3600)
m = ((padd_sec + pc_sec + gb_sec) - (h * 3600)) // 60
s = ((padd_sec + pc_sec + gb_sec) - ((h * 3600) + (m * 60)))

print("You need to distract the guard's attention for", int(h), "hour(s),", int(m), "minute(s) and", format(s, ".2f"), "second(s).")

